"""QT application boundaries: ordered persistence, evidence and evaluation.

Application policies own authorization/selection/state transitions. Implementors
own SQL, canonical source proof, governed input reads and evaluator execution.
No implementation is selected or constructed in this module.
"""
from collections.abc import Mapping, Sequence
from contextlib import AbstractContextManager
from datetime import date
from typing import Any, Protocol


class QtTransactionPort(Protocol):
    book_id: str
    def lock_authorities(self, identities: Sequence[int]) -> Sequence[Mapping[str, Any]]: ...
    def registry_ids_for_book(self) -> tuple[str, ...]: ...
    def lock_registries(self, identities: Sequence[str]) -> Sequence[Mapping[str, Any]]: ...
    def lock_books(self, identities: Sequence[str]) -> None: ...
    def utc_source_day(self) -> date: ...
    def lock_mutable(self, **scope: Any) -> None: ...
    def read_current_facts(self, *, actor_id: int | None = None) -> dict[str, Any]: ...
    def read_source_evidence(self) -> Mapping[str, Any]: ...
    def approval_authority(self, actor_id: int) -> Mapping[str, Any]: ...
    def capability(self) -> Mapping[str, Any]: ...
    def resolve_instrument_types(self, keys: Sequence[Any]) -> Mapping[Any, str]: ...
    def get_draft_head(self, source_day: date) -> Mapping[str, Any] | None: ...
    def get_preview(self, preview_id: str) -> Mapping[str, Any] | None: ...
    def get_receipt(self, decision_id: str) -> Mapping[str, Any] | None: ...
    def get_idempotent(self, operation: str, scope: str, key: str, digest: str) -> Mapping[str, Any] | None: ...
    def insert_idempotent(self, operation: str, scope: str, key: str, digest: str, response: Mapping[str, Any]) -> None: ...
    def insert_draft_revision(self, data: Mapping[str, Any]) -> str: ...
    def advance_draft_head(self, source_day: date, expected_revision: int, draft_id: str, revision: int) -> None: ...
    def insert_preview(self, data: Mapping[str, Any]) -> Any: ...
    def insert_decision(self, data: Mapping[str, Any]) -> Any: ...
    def insert_override_request(self, data: Mapping[str, Any]) -> Any: ...
    def insert_approval(self, data: Mapping[str, Any]) -> Any: ...
    def consume_preview(self, preview_id: str, expected_state: str, new_state: str) -> None: ...
    def read_evaluation_policy(self) -> Mapping[str, Any] | None: ...
    def get_override_context(self, request_id: str) -> Mapping[str, Any]: ...
    def promote_decision(self, decision_id: str) -> None: ...


class QtWorkflowRepositoryPort(Protocol):
    def transaction(self, book_id: str, actor_id: int) -> AbstractContextManager[QtTransactionPort]: ...
    def preview_routing(self, preview_id: str) -> Mapping[str, Any]: ...
    def override_routing(self, request_id: str) -> Mapping[str, Any]: ...


class QtDecisionReadRepositoryPort(QtWorkflowRepositoryPort, Protocol):
    def decision_routing(self, decision_id: str) -> Mapping[str, Any]: ...
    def latest_routing(self, book_id: str, source_day: date | None) -> tuple[date, Mapping[str, Any] | None]: ...


class QtEvidencePort(Protocol):
    def reconcile_source(self, book_id: str, source_day: date, publications: Sequence[Mapping[str, Any]],
                         rows: Sequence[Mapping[str, Any]], audits: Sequence[Mapping[str, Any]], **observed: Any) -> Any: ...
    def capture_read_set(self, facts: Mapping[str, Any]) -> Any: ...
    def canonical_snapshot(self, kind: str, payload: Mapping[str, Any]) -> bytes: ...
    def input_bytes(self, payload: Mapping[str, Any]) -> bytes: ...
    def prove_report(self, evidence: Mapping[str, Any]) -> None: ...


class QtInputLoaderPort(Protocol):
    def load(self, tx: QtTransactionPort, *, source_day: date, model_publication_id: str,
             checked_at: Any) -> Any: ...


class QtEvaluatorClientPort(Protocol):
    def validate_request(self, request: Mapping[str, Any]) -> None: ...
    def evaluate(self, request: Mapping[str, Any]) -> Any: ...


class QtEvaluatorPort(Protocol):
    bundle_directory: Any
    executable: Any
    def create_client(self, inputs: Any) -> QtEvaluatorClientPort: ...


class QtAuthorizationPort(Protocol):
    def resolve(self, actor_id: int, tx: QtTransactionPort) -> Any: ...
    def quorum(self, people: Sequence[Any]) -> bool: ...


class QtDecisionReadQueriesPort(Protocol):
    """Every operation borrows the already ordered, locked transaction."""
    def decision_context(self, tx: QtTransactionPort, decision_id: str, book_id: str) -> Mapping[str, Any]: ...
    def latest_decision_id(self, tx: QtTransactionPort, book_id: str, source_day: date) -> str | None: ...
    def publication_evidence(self, tx: QtTransactionPort, context: Mapping[str, Any], preview: Mapping[str, Any],
                             receipt: Mapping[str, Any], facts: Mapping[str, Any]) -> Mapping[str, Any]: ...
    def enabled_prerequisites(self, tx: QtTransactionPort, bundle_directory: Any) -> bool: ...
    def require_legacy_disabled(self, tx: QtTransactionPort) -> None: ...
