# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from algogators import desk_pb2 as algogators_dot_desk__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in algogators/desk_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DeskServiceStub:
    """The health service is the standard grpc.health.v1.Health (grpc_health/v1/health.proto),
    registered by the shared server next to every service. Service name for a targeted check:
    "algogators.desk.DeskService"; "" checks the server as a whole.

    Version history (bump Version above; a major bump is a breaking change, see docs/design/rpc.md):
    1.0.0  2026-10-09  first versioned release. Same messages and field numbers as the earlier
    unversioned algogators.qt.v1 package, so the wire format is unchanged.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunDesk = channel.unary_unary(
                '/algogators.desk.DeskService/RunDesk',
                request_serializer=algogators_dot_desk__pb2.RunDeskRequest.SerializeToString,
                response_deserializer=algogators_dot_desk__pb2.RunDeskReply.FromString,
                _registered_method=True)
        self.RequestOverride = channel.unary_unary(
                '/algogators.desk.DeskService/RequestOverride',
                request_serializer=algogators_dot_desk__pb2.OverrideRequest.SerializeToString,
                response_deserializer=algogators_dot_desk__pb2.CommandReply.FromString,
                _registered_method=True)
        self.RecordDecision = channel.unary_unary(
                '/algogators.desk.DeskService/RecordDecision',
                request_serializer=algogators_dot_desk__pb2.DecisionRequest.SerializeToString,
                response_deserializer=algogators_dot_desk__pb2.CommandReply.FromString,
                _registered_method=True)
        self.Publish = channel.unary_unary(
                '/algogators.desk.DeskService/Publish',
                request_serializer=algogators_dot_desk__pb2.PublishRequest.SerializeToString,
                response_deserializer=algogators_dot_desk__pb2.CommandReply.FromString,
                _registered_method=True)
        self.GetRunStatus = channel.unary_unary(
                '/algogators.desk.DeskService/GetRunStatus',
                request_serializer=algogators_dot_desk__pb2.RunStatusRequest.SerializeToString,
                response_deserializer=algogators_dot_desk__pb2.RunStatus.FromString,
                _registered_method=True)


class DeskServiceServicer:
    """The health service is the standard grpc.health.v1.Health (grpc_health/v1/health.proto),
    registered by the shared server next to every service. Service name for a targeted check:
    "algogators.desk.DeskService"; "" checks the server as a whole.

    Version history (bump Version above; a major bump is a breaking change, see docs/design/rpc.md):
    1.0.0  2026-10-09  first versioned release. Same messages and field numbers as the earlier
    unversioned algogators.qt.v1 package, so the wire format is unchanged.

    """

    def RunDesk(self, request, context):
        """A desk save: run the desk loop on the whole qt_proposal and book the result as qt with
        source=desk, per-symbol asked/given/step (plan 3b; plan E5/E6). Never sends mail
        (ruling 15). Refused when no proposal has been seeded for the day (ruling 14).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RequestOverride(self, request, context):
        """E-mails the VP and the President a signed, single-use approval link for a breaching
        selection (D4, D5; plan A5/E7).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordDecision(self, request, context):
        """A link click recorded by AlgoLens; on approval the engine books the override as qt with
        source=override (D5, D17; plan 3b Q3).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Publish(self, request, context):
        """Finalise the day's qt book, send the e-mail and CSV, write published_by/published_at on
        trading.live_run_metadata (D7; plan A6/E8). A missed day is caught up first (ruling 29).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRunStatus(self, request, context):
        """The model run's state for one book and day, read from trading.live_run_metadata, for the
        desk pages (AlgoLens #97). Read-only; D18: no desk window opens unless the run succeeded.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeskServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunDesk': grpc.unary_unary_rpc_method_handler(
                    servicer.RunDesk,
                    request_deserializer=algogators_dot_desk__pb2.RunDeskRequest.FromString,
                    response_serializer=algogators_dot_desk__pb2.RunDeskReply.SerializeToString,
            ),
            'RequestOverride': grpc.unary_unary_rpc_method_handler(
                    servicer.RequestOverride,
                    request_deserializer=algogators_dot_desk__pb2.OverrideRequest.FromString,
                    response_serializer=algogators_dot_desk__pb2.CommandReply.SerializeToString,
            ),
            'RecordDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordDecision,
                    request_deserializer=algogators_dot_desk__pb2.DecisionRequest.FromString,
                    response_serializer=algogators_dot_desk__pb2.CommandReply.SerializeToString,
            ),
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=algogators_dot_desk__pb2.PublishRequest.FromString,
                    response_serializer=algogators_dot_desk__pb2.CommandReply.SerializeToString,
            ),
            'GetRunStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRunStatus,
                    request_deserializer=algogators_dot_desk__pb2.RunStatusRequest.FromString,
                    response_serializer=algogators_dot_desk__pb2.RunStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'algogators.desk.DeskService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('algogators.desk.DeskService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DeskService:
    """The health service is the standard grpc.health.v1.Health (grpc_health/v1/health.proto),
    registered by the shared server next to every service. Service name for a targeted check:
    "algogators.desk.DeskService"; "" checks the server as a whole.

    Version history (bump Version above; a major bump is a breaking change, see docs/design/rpc.md):
    1.0.0  2026-10-09  first versioned release. Same messages and field numbers as the earlier
    unversioned algogators.qt.v1 package, so the wire format is unchanged.

    """

    @staticmethod
    def RunDesk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/algogators.desk.DeskService/RunDesk',
            algogators_dot_desk__pb2.RunDeskRequest.SerializeToString,
            algogators_dot_desk__pb2.RunDeskReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RequestOverride(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/algogators.desk.DeskService/RequestOverride',
            algogators_dot_desk__pb2.OverrideRequest.SerializeToString,
            algogators_dot_desk__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/algogators.desk.DeskService/RecordDecision',
            algogators_dot_desk__pb2.DecisionRequest.SerializeToString,
            algogators_dot_desk__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/algogators.desk.DeskService/Publish',
            algogators_dot_desk__pb2.PublishRequest.SerializeToString,
            algogators_dot_desk__pb2.CommandReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRunStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/algogators.desk.DeskService/GetRunStatus',
            algogators_dot_desk__pb2.RunStatusRequest.SerializeToString,
            algogators_dot_desk__pb2.RunStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
