"""Generated by gen_versions.py from the version header of each proto/algogators/*.proto.

Do not edit: change the "Version:" line of the .proto and regenerate.
"""

API_VERSIONS = {
    "common": "1.0.0",
    "desk": "1.1.0",
}
